### PR TITLE
Support for Session Affinity option in service template

### LINKED ISSUE #4: Option to configure the sessionAffinity and sessionAffinityConfig
It would be cool to configure the sessionAffinity and sessionAffinityConfig for the service in this helm chart.

### PR DESCRIPTION
**Pull request by Skaronator**
Fixes #4

### CODE REVIEW

**Review by canterberry — APPROVED** [review]
:+1: LGTM. Concise and complete.

**Comment by Skaronator** [comment]
@canterberry Thanks for the quick review. Sadly the release doesn't seem to be available via helm.

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "twuni" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo twuni/docker-registry -l
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                     
twuni/docker-registry	1.9.7        	2.7.1      	A Helm chart for Docker Registry
twuni/docker-registry	1.9.6        	2.7.1      	A Helm chart for Docker Registry
```

**Comment by canterberry** [comment]
New version hasn't been released, yet. Looking to land #6 first, but I suppose it wouldn't hurt to push this out atomically!

**Comment by canterberry** [comment]
There we go. New version has been released.

```bash
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "twuni" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo twuni/docker-registry -l
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
twuni/docker-registry   1.10.0          2.7.1           A Helm chart for Docker Registry
twuni/docker-registry   1.9.7           2.7.1           A Helm chart for Docker Registry
twuni/docker-registry   1.9.6           2.7.1           A Helm chart for Docker Registry
```

**Pull request merged**
