### PR TITLE
Corrected docker htpasswd command

### PR DESCRIPTION
**Pull request by fritzduchardt**
Current command does not work anymore - probably due to changes in underlying image. New comes from official docker documentation and works fine.

### CODE REVIEW

**Review by canterberry — APPROVED** [review]
LGTM. Thank you!

**Comment by ctr26** [comment]
`docker run --rm -ti xmartlabs/htpasswd username password >> ./htpasswd`

This worked for me (from https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-top-of-digitalocean-spaces-and-use-it-with-digitalocean-kubernetes)

`docker run --entrypoint htpasswd httpd:2 -Bbn user password > ./htpasswd`

This did not

**Comment by SimonRupar** [comment]
@fritzduchardt, I see that this MR is already approved, but needs signed git commits. Can you please sign your commits?

**Comment by brsolomon-deloitte** [comment]
Closes #30

**Comment by canterberry** [comment]
Closing this PR, as it seems to have been abandoned without having addressed the feedback given.

**Pull request closed without merging**
