### PR TITLE
Garbage collector cronjob

### PR DESCRIPTION
**Pull request by kuzaxak**
Please check additional information in commit messages.

Garbage collector job was added to registry [here][1]

[1]: https://github.com/distribution/distribution/pull/2302

### CODE REVIEW

**Comment by ddelange** [comment]
Hi @kuzaxak 👋 

Two questions:
- Could you bring your branch up to date with `twuni:main`?
- What do you think about handling dangling images due to overwritten tags? ref https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup#why-does-this-happen

**Comment by kuzaxak** [comment]
> * Could you bring your branch up to date with `twuni:main`?

Yes, will do it on weekends. 

> What do you think about handling dangling images due to overwritten tags? ref https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup#why-does-this-happen also cc @canterberry

Wasn't it added in [PR](https://github.com/distribution/distribution/pull/2302)? If not then an external cleanup script can be used as well.

**Comment by ddelange** [comment]
Awesome!

With regards to your question, I'm not sure to be honest. The repo has been maintained after that PR was merged, the repo also points to some open issues. I don't remember in which article I found this repo suggested as a good preparation step before running garbage collection, so can't verify dates on that one...

**Comment by ddelange** [comment]
> Wasn't it added in [PR](https://github.com/distribution/distribution/pull/2302)?

@kuzaxak I think you are right! I opened https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup/issues/25 just to double check.

**Comment by ddelange** [comment]
Until this gets released, this can be installed with
```
helm install --namespace ... https://github.com/ddelange/docker-registry.helm/releases/download/v2.2.0/helm-chart-docker-registry-2.2.0.tgz
```

**Pull request merged**
