### PR TITLE
fix extraVolumes and extraVolumeMounts (hypen typo) 

### PR DESCRIPTION
**Pull request by pieveee**
See bug report https://github.com/twuni/docker-registry.helm/issues/73

### CODE REVIEW

**Comment by pieveee** [comment]
@canterberry There we go. Sorry for the inconvenience! 😅

**Comment by canterberry** [comment]
Hmm... the core diff looks fine, but I'm seeing a whole-file diff for whitespace changes. Is it saved with `\r\n` line-feeds, maybe?

**Comment by pieveee** [comment]
Uff... What do you normally use? My vs code is on CRLF.

**Comment by canterberry** [comment]
> Uff... What do you normally use? My vs code is on CRLF.

[Git](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) has a setting for it, and [VS code](https://blog.boot.dev/clean-code/line-breaks-vs-code-lf-vs-crlf/), at least, has a toggle in the status bar for it (though I'd expect it to respect the file's native line endings and/or the git configuration).

**Comment by pieveee** [comment]
Yeah, I am aware of the toggle in the bottom right corner of vs code. But it shouldn't alter automatically as you have already stated. 🤔 
image

Do you want me to change it to LF?

**Comment by canterberry** [comment]
> Yeah, I am aware of the toggle in the bottom right corner of vs code. But it shouldn't alter automatically as you have already stated. thinking image
> 
> Do you want me to change it to LF?

An identical diff to [this one on #74](https://github.com/twuni/docker-registry.helm/pull/74/files) is what I would like to see in this PR. Beyond that, I have no opinion on how to achieve it and whether that's through git settings, IDE settings, or otherwise. Whatever's best for you.

**Pull request closed without merging**
