### PR TITLE
added support for ingress in k8s 1.22+

### PR DESCRIPTION
**Pull request by devfaz**

### CODE REVIEW

**Review by canterberry — COMMENTED** [review]
Seems good to me; please provide details in the PR description, and for this particular change because it impacts compatibility, with which K8s versions the resulting chart has been verified compatible. Mainly interested in minimum supported version, and that each version since is compatible.

**Comment by canterberry** [comment]
Duplicates #27.

**Comment by canterberry** [comment]
Fixes #19.

**Comment by ElArtista** [comment]
Any updates on when will this be merged?

**Comment by canterberry** [comment]
Waiting for the author to respond.

As a general rule, I don't merge MRs without some due diligence in communication from the author, particularly after feedback is given and left unaddressed.

**Comment by ElArtista** [comment]
Seems that the author (@devfaz) hasn't been active in the last few months.
This PR is crucial, cause it makes the chart usable for all the latest k8s versions.
Is there something else we can do about it?

**Comment by devfaz** [comment]
@ElArtista  thx for the trigger... 

Even if I dont get why my missing answer is not allowing any merge.

LMGTFY: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

So it will no longer work with k8s <1.16, but start working for k8s >= 1.22.

For the future I would suggest to handle new commiters a bit more friendly, than - maybe - they will continue to try improving the code. Thats how opensource works - we all provide work/time for free and should appricate each others work as much as possible.

**Comment by canterberry** [comment]
Closing, as the author is in violation of contribution guidelines.

**Pull request closed without merging**
