### PR TITLE
fix extraVolumes and extraVolumeMounts (hypen typo)

### LINKED ISSUE #73: Chart 2.2.1 Update Failed
Hi,
I tried to update to the latest version of the chart today, however I get the error:
`Error: UPGRADE FAILED: YAML parse error on docker-registry/templates/deployment.yaml: error converting YAML to JSON: yaml: line 80: mapping values are not allowed in this context`
Is this likely an issue with my custom values.yaml?
No issues with 2.2.0.
Thank you.

### PR DESCRIPTION
**Pull request by pieveee**
See bug report https://github.com/twuni/docker-registry.helm/issues/73

### CODE REVIEW

**Review by canterberry — APPROVED** [review]
:+1: LGTM. Thanks for fixing this!

> :bulb: As a follow-up, we should probably add something in the smoke test to account for `extra____` values (environment variables, volumes, etc). I'll create an issue for that.

**Comment by canterberry** [comment]
Smoke-tested this locally. Was able to reproduce the issue on the target branch, saw correct output on base branch.

```bash
$ cat values.test.yaml
---
extraVolumes:
- name: foo
  emptyDir: {}
extraVolumeMounts:
- name: foo
  mountPath: /foo
$ helm upgrade --install --namespace meta-namespace --set namespace=target-namespace --dry-run --values values.test.yaml release-name .
...
          volumeMounts: 
            - name: "chart-name-docker-registry-config"
              mountPath: "/etc/docker/registry"
            - name: data
              mountPath: /var/lib/registry/
            - mountPath: /foo
              name: foo
      volumes: 
        - name: chart-name-docker-registry-config
          configMap:
            name: chart-name-docker-registry-config
        - name: data
          emptyDir: {}
        - emptyDir: {}
          name: foo
```

**Comment by canterberry** [comment]
cc @ddelange FYI Something's not quite right with the GH action. It seems to be running once for `pull_request_target` and again for `pull_request` (the latter asked for my permission to run because pieveee is a first-time contributor in this repo), and the latter one fails. I'll see if I can fix that and assign you for review.

In the meantime, I'll use my privileges to bypass branch protection since the failing check is a duplicate.

**Comment by canterberry** [comment]
@pieveee Would you mind [signing your commits](https://docs.github.com/articles/about-gpg/) and force-pushing to this branch? I'd like to push your fix, but that is one protection I'd prefer not to bypass.

**Comment by pieveee** [comment]
@canterberry Setting up the signature verification with gpg was a bit of a hassle^^ I will rewrite the pull-request as I messed things up a bit here.

**Comment by canterberry** [comment]
I appreciate it, @pieveee . Thanks for following through! :muscle: (I see the latest commits are showing as *Verified* so should be good to go on the new PR)

**Pull request closed without merging**
