### PR TITLE
Adding Deployment Annotations

### LINKED ISSUE #86: Adding annotations for deployment to values
It would be very great to have annotations for the deployment itself. As there is currently no way to do that, we would have to clone and integrate the entire chart into our parent chart which is a mess just to change a few lines there.

For example the wave project for kubernetes requires a certain annotation on deployments / statefulsets in order to be active.
As there are annotations available for almost all other resources that would be a great minor addition which would help a lot!

### PR DESCRIPTION
**Pull request by ChevronTango**
Closes #86

This adds the ability for users to specify annotations on the deployment.

### CODE REVIEW

**Review by joshsizer — APPROVED** [review]
@ChevronTango This looks good to me.

@vyas-n What do you think?

**Comment by joshsizer** [comment]
@ChevronTango Could you recommit these changes with signed commits? 

This comment has some resources to help with that if you need it: https://github.com/twuni/docker-registry.helm/pull/93#issuecomment-1979504730

**Review by vyas-n — APPROVED** [review]

**Comment by vyas-n** [comment]
Looks good to me, just needs signed commits before it can be merged 👍🏽

**Comment by ChevronTango** [comment]
Just pushed up a signed commit using Sigstore, however GitHub doesn't formally support those signatures yet, despite them being valid and secure. Hopefully that doesn't prevent the merge going ahead. If it does I'll resign using a GPG key.

**Comment by joshsizer** [comment]
@ChevronTango Unfortunately GitHub is still saying that the commits need to be signed. Could you go ahead and commit them again with GPG/SSH?

**Comment by ChevronTango** [comment]
@joshsizer that should be all ready to go now

**Comment by joshsizer** [comment]
> @joshsizer that should be all ready to go now

Thank you!

**Pull request merged**
