### PR TITLE
Add initContainer support

### PR DESCRIPTION
**Pull request by g-linville**
This commit will give the user the ability to specify initContainers directly in the values file, which will then become part of the deployment.

### CODE REVIEW

**Comment by weisjohn** [comment]
@g-linville I'd love to see this land in the chart. Can you provide some more of the rationale as to why you need this?

**Comment by g-linville** [comment]
> @g-linville I'd love to see this land in the chart. Can you provide some more of the rationale as to why you need this?

Thanks @weisjohn. The reason I need this is to adjust file permissions of the registry directory by using `chown` to change ownership to a different user, since I am running the container as a non-root user.

@twuni if you would be willing to merge this, that would be great! I appreciate this Helm chart quite a lot, since it provides such an easy way to run the Docker Registry inside of k8s.

**Review by izorster — DISMISSED** [review]
This seems reasonable

**Review by canterberry — CHANGES_REQUESTED** [review]
Can you add docs to the table in the README for this new value? Then, LGTM as well.

**Comment by g-linville** [comment]
@canterberry done!

**Review by canterberry — DISMISSED** [review]

**Comment by g-linville** [comment]
@canterberry I had to force-update my branch so I could sign my commits with GPG. Can you re-approve? Sorry for the inconvenience.

**Review by canterberry — APPROVED** [review]

**Comment by weisjohn** [comment]
@canterberry do you think you could release this?

**Pull request merged**
